version: '3.8'
services:
  lavague:
    image: lavague
    user: 1000:1000
    volumes:
      - /home/$USER/LaVague/lavague-files:/home/vscode/lavague-files
    ports:
      - "7860:7860"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: ["./entrypoint.sh"]